// authentication
const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN';

// profile
const SET_PROFILE = 'SET_PROFILE';
const UPDATE_PROFILE = 'UPDATE_PROFILE';

// theme type
const TOGGLE_THEME_BEGIN = 'TOGGLE_THEME_BEGIN';
const TOGGLE_THEME_SUCCESS = 'TOGGLE_THEME_SUCCESS';
const TOGGLE_THEME_FAILURE = 'TOGGLE_THEME_FAILURE';

export {
  SET_ACCESS_TOKEN,
  REMOVE_ACCESS_TOKEN,
  TOGGLE_THEME_BEGIN,
  TOGGLE_THEME_SUCCESS,
  TOGGLE_THEME_FAILURE,
  SET_PROFILE,
};
