// authentication
const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
const REMOVE_ACCESS_TOKEN = 'REMOVE_ACCESS_TOKEN';

// profile
const GET_PROFILE = 'GET_PROFILE';
const UPDATE_PROFILE = 'UPDATE_PROFILE';

// theme type
const TOGGLE_THEME_BEGIN = 'TOGGLE_THEME_BEGIN';
const TOGGLE_THEME_SUCCESS = 'TOGGLE_THEME_SUCCESS';
const TOGGLE_THEME_FAILURE = 'TOGGLE_THEME_FAILURE';

// products favorite
const SET_PRODUCTS_FAVORITE = 'SET_PRODUCTS_FAVORITE';
const REMOVE_PRODUCTS_FAVORITE = 'REMOVE_PRODUCTS_FAVORITE';

// cart
const ADD_TO_CART = 'ADD_TO_CART';
const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
const GET_NUMBER_CART = 'GET_NUMBER_CART';
const SET_CARTS = 'SET_CARTS';
const REMOVE_ALL_CARTS = 'REMOVE_ALL_CARTS';

// order
const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY';

// category
const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
const GET_PRODUCT_BY_CATEGORY = 'GET_PRODUCT_BY_CATEGORY';

// product
const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';

export {
  SET_ACCESS_TOKEN,
  REMOVE_ACCESS_TOKEN,
  TOGGLE_THEME_BEGIN,
  TOGGLE_THEME_SUCCESS,
  TOGGLE_THEME_FAILURE,
  SET_PRODUCTS_FAVORITE,
  REMOVE_PRODUCTS_FAVORITE,
  GET_PROFILE,
  ADD_TO_CART,
  INCREMENT_QUANTITY,
  DECREMENT_QUANTITY,
  REMOVE_FROM_CART,
  GET_NUMBER_CART,
  SET_CARTS,
  REMOVE_ALL_CARTS,
  GET_ORDER_HISTORY,
  GET_ALL_CATEGORY,
  GET_PRODUCT_BY_CATEGORY,
  GET_ALL_PRODUCT,
};
